apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitops-prod-operator
  namespace: prod
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: gitops
          containers:
            - name: gitops-operator
              image: sandervanvugt/gittools
              volumeMounts:
                - mountPath: /prod
                  name: prod
              command: [sh, -e, -c]
              args:
                - git clone https://github.com/sandervanvugt/prod /prod || (cd /prod && git pull) && 
                  find /prod -name '*.yaml' -exec kubectl apply -f {} \;
         volumes:
           - name: prod
             hostPath:
               path: /prod
