kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-preprod
  labels:
      type: local
spec:
  storageClassName: preprod
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /preprod
