kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-prod
  labels:
      type: local
spec:
  storageClassName: prod
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /prod
