apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demopipe
spec:
  params:
  - name: username
    type: string
  tasks:
  - name: demotask
    taskRef:
      name: demotask
  - name: secondtask
    runAfter:
    - demotask
    taskRef:
      name: secondtask
    params:
    - name: username
      value: $(params.username)
