kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvpreprod
  labels:
      type: local
spec:
  storageClassName: preproduction
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /preprod
