kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvprod
  labels:
      type: local
spec:
  storageClassName: production
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /production
