apiVersion: apps/v1
kind: Deployment
metadata: 
  name: demo-app
spec:
  template:
    spec:
      containers:
        - name: nginx
          env:
            - name: STATUS
              value: "kustomized"
